---
title: 'SIDC: Decade: 2009 -2019'
author: "David J Jackson"
date: "1/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(prophet)
```
```{r import_data,echo=TRUE}
rm(list=ls())
## Read Data: 
isn <-fread("http://sidc.be/silso/DATA/SN_d_tot_V2.0.csv",sep=";")
colnames(isn) <- c("Year","Month","Day", "Fdate","Spots", "Sd","Obs" ,"Defin" )
# Add an explicit date feature to the data frame.
isn$Ymd <- as.Date(paste(isn$Year, isn$Month, 
                         isn$Day, sep = "-"))
## Add Yes and No counts.
isn$Cts <- ifelse(isn$Spots <=0,"No","Yes")
## Create Yes/No Chart by Year: Falim Ahmad
data.frame(table(isn$Cts)) %>% 
  ggplot(aes(x=Var1,y=Freq,fill=Var1)) +
  geom_col() + labs(title="Ratio of Days w/wo Spots: 1850-2019")

isn_d <- isn %>% filter(Year >=2009 & Year <=2019) %>% select(Year,Month,Spots,Sd,Cts,Obs)
  ggplot(data=isn_d,aes(x=Cts , fill=Cts ))+
  geom_histogram(stat="count") + labs(title="Ratio of Days w/wo Spots: 2009-2019") + facet_wrap(~Year)
#Begin Decade calc: 2009 - 2019

## Spots vs Sd
ggplot(data=isn_d,aes(x=Sd,y=Spots)) +geom_point() + facet_wrap(~Year) +
  ggtitle("Summary of SD vs ISN by Year and Month:2009 - 2019") +
   ylab("Internation Sunbspot Number") + xlab("Standard Deviation") +
  geom_smooth(method="glm")
```
```{r Prophet, echo=TRUE}
df<-isn[Ymd >="1850-01-01" ,.(Ymd,Spots)]
colnames(df) <- c("ds","y")
m <- prophet(seasonality.mode="multiplicative")
m <- add_seasonality(m, name="cycle_11year", period=365.25 * 11,fourier.order=5)
m <- fit.prophet(m, df)
future <- make_future_dataframe(m,periods=4000,freq="day")
forecast <- predict(m, future)
plot(m, forecast) +ggtitle("SIDC Sunspot Prediction: Jan. 1810 - May. 2022")
```
```{r Cycle_25_Beyond.echo=TRUE}
## Cycle 25 and Beyond
forecast <- as.data.table(forecast)
forecast1 <- forecast[ds >="2019-01-01"  &  ds <="2022-12-31",]
ggplot(data=forecast1,aes(x=ds,y=yhat)) +geom_line() +
  geom_smooth() +   ggtitle("SIDC: Cycle 25 and  Beyond: 2019 - 2022")
```
```{r Cycle_25_Beyond.echo=TRUE}
## Cycle 25 and Beyond
forecast <- as.data.table(forecast)
forecast1 <- forecast[ds >="2019-01-01"  &  ds <="2022-12-31",]
ggplot(data=forecast1,aes(x=ds,y=yhat)) +geom_line() +
  geom_smooth() +   ggtitle("SIDC: Cycle 25 and  Beyond: 2019 - 2022")
```
```{r sidc-vs-kanzel}
df2<-isn[Ymd >="1944-05-29" ,.(Ymd,Spots)]
colnames(df2) <- c("ds","y")
m <- prophet(seasonality.mode="multiplicative")
m <- add_seasonality(m, name="cycle_11year", period=365.25 * 11,fourier.order=5)
m <- fit.prophet(m, df2)
future2 <- make_future_dataframe(m,periods=4000,freq="day")
forecast2 <- predict(m, future2)
plot(m, forecast2) +ggtitle("SIDC Sunspot Prediction: May. 1944 - May. 2022")
```
```{r}
forecast2 <- as.data.table(forecast2)
forecast2 <- forecast2[ds >="2019-01-01"  &  ds <="2022-12-31",]
ggplot(data=forecast2,aes(x=ds,y=yhat)) +geom_line() +
  geom_smooth() +   ggtitle("SIDC: Cycle 25 and  Beyond: 2019 - 2022")
```

